import groovy.transform.Field

@Field final String nodeVersion = '10.4.1'
@Field final String yarnVersion = '1.10.1'
@Field final String yarnPath = './node_modules/.bin/yarn'

def windowsStep () {
  node(label: 'windows') {
    ansiColor('xterm') {
      bat 'git config --global core.autocrlf input'
      checkout scm
      fileExists 'package.json'
      nodejs(nodeVersion) {
        bat 'del /s /q node_modules >nul 2>&1'
        bat "npm install yarn@${yarnVersion}"
        bat "${yarnPath} config set msvs_version 2015 --global"
        bat "${yarnPath} --mutex network"
        bat "${yarnPath} lint"
        bat "${yarnPath} build"
        archiveArtifacts 'dist\\*'
        cleanWs()
      }
    }
  }
}

def unixStep(nodeLabel) {
  node(label: nodeLabel) {
    ansiColor('xterm') {
      checkout scm
      fileExists 'package.json'
      nodejs(nodeVersion) {
        sh 'rm -rf node_modules/'
        sh "npm install yarn@${yarnVersion}"
        sh "${yarnPath} --mutex network"
        sh "${yarnPath} lint"
        sh "${yarnPath} build"
        archiveArtifacts 'dist/*'
        cleanWs()
      }
    }
  }
}

stage('Builds') {
  parallel(
    "windows": { windowsStep() },
    "macos": { unixStep("macos") },
    "linux": { unixStep("linux") }
  )
}
