export type CONFIG_KEYS =
  | 'AUTO_LAUNCH'
  | 'AUTO_GARBAGE_COLLECTOR'
  | 'DISABLE_AUTO_UPDATE'
  | 'SCREENSHOT_SHORTCUT'
  | 'OPEN_WEBUI_LAUNCH'
  | 'MONOCHROME_TRAY_ICON'
  | 'EXPERIMENT_PUBSUB'
  | 'EXPERIMENT_PUBSUB_NAMESYS'
